apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ai-app.fullname" . }}-backend-secrets
  labels:
    {{- include "ai-app.backend.labels" . | nindent 4 }}
type: Opaque
# stringData allows us to use literal strings in the values.yaml without needing to base64 encode them
stringData:
  AZURE_OPENAI_ENDPOINT: {{ .Values.backend.secrets.azureOpenAI.endpoint }}
  AZURE_OPENAI_API_KEY: {{ .Values.backend.secrets.azureOpenAI.apiKey }}
  AZURE_OPENAI_DEPLOYMENT_NAME: {{ .Values.backend.secrets.azureOpenAI.deploymentName }}
  AZURE_OPENAI_MODEL: {{ .Values.backend.secrets.azureOpenAI.model }}
  AZURE_COSMOSDB_ENDPOINT: {{ .Values.backend.secrets.cosmosDB.endpoint }}
  AZURE_COSMOSDB_KEY: {{ .Values.backend.secrets.cosmosDB.key }}
  AZURE_SEARCH_ENDPOINT: {{ .Values.backend.secrets.search.endpoint }}
  AZURE_SEARCH_API_KEY: {{ .Values.backend.secrets.search.apiKey }}
  {{- if .Values.postgresql.auth.username }}
  POSTGRESQL_USER: {{ .Values.postgresql.auth.username }}
  {{- end }}
  {{- if .Values.postgresql.auth.password }}
  POSTGRESQL_PASSWORD: {{ .Values.postgresql.auth.password }}
  {{- end }}
  {{- if .Values.azure.applicationInsights.enabled }}
  APPLICATIONINSIGHTS_CONNECTION_STRING: {{ .Values.azure.applicationInsights.connectionString }}
  {{- end }}
---
