{{- if and .Values.gateway.tls.enabled .Values.gateway.tls.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.gateway.tls.secretName }}
  labels:
    {{- include "ai-app.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.gateway.tls.crt | b64enc | quote }}
  tls.key: {{ .Values.gateway.tls.key | b64enc | quote }}
{{- end }}
